name: firebase_functions_interop_test
description: Test Firebase Functions Interop
version: 0.0.0
#homepage: https://www.example.com
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  firebase_functions_interop:
    path: ../

dev_dependencies:
  build_runner: ^1.7.4
  build_node_compilers:
    git:
      url: https://github.com/blaueeiner/node-interop
      path: ./build_node_compilers/
      ref: feature/update-dependencies
