name: firebase_functions_interop
description: Firebase Cloud Functions SDK for Dart written as a JS interop wrapper for official Node.js SDK.
version: 2.0.0
homepage: https://www.github.com/pulyaevskiy/firebase-functions-interop
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  js: ^0.6.3
  meta: ^1.3.0
  node_interop:
    git:
      url: https://github.com/blaueeiner/node-interop
      path: ./node_interop/
      ref: master
  node_io:
    git:
      url: https://github.com/blaueeiner/node-interop
      path: ./node_io/
      ref: master
  node_http:
    git:
      url: https://github.com/blaueeiner/node-interop
      path: ./node_http/
      ref: master
  firebase_admin_interop:
    git:
      url: https://github.com/blaueeiner/firebase-admin-interop.git
      ref: feature/null-safety-compatibility

dev_dependencies:
  test: ^1.16.8
